import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import {
  deleteSellerProduct,
  getSellerProducts,
  updateSellerProduct,
} from "../../api/marketplaceApi";
import {
  MarketplaceDashboardShell,
  MarketplaceImage,
  StateBlock,
  formatCurrency,
  getErrorMessage,
} from "./MarketplaceShared";

const statusFilters = [
  { key: "all", label: "All Products" },
  { key: "active", label: "Active" },
  { key: "draft", label: "Drafts" },
];

const getEcoLabel = (score) => {
  if (!score) return "Pending";
  if (score >= 90) return "Excellent";
  if (score >= 75) return "High";
  if (score >= 60) return "Good";
  return "Needs Work";
};

export default function SellerProducts() {
  const [products, setProducts] = useState([]);
  const [stats, setStats] = useState({ total: 0, active: 0, drafts: 0, co2_total: 0, average_carbon_saved: 0, average_eco_score: 0 });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("all");

  const loadProducts = async () => {
    try {
      setLoading(true);
      setError("");
      const response = await getSellerProducts();
      setProducts(response.data.products || []);
      setStats(response.data.stats || {});
    } catch (err) {
      setError(getErrorMessage(err, "Failed to load seller products."));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadProducts();
  }, []);

  const filteredProducts = useMemo(() => {
    const search = query.trim().toLowerCase();
    return products.filter((product) => {
      const matchesStatus = filter === "all" || product.status === filter;
      const matchesSearch =
        !search ||
        [product.name, product.category, product.sku]
          .filter(Boolean)
          .some((value) => String(value).toLowerCase().includes(search));
      return matchesStatus && matchesSearch;
    });
  }, [products, query, filter]);

  const averageCarbonSaved = useMemo(() => {
    if (stats.average_carbon_saved !== undefined && stats.average_carbon_saved !== null) {
      return Number(stats.average_carbon_saved || 0);
    }

    if (!products.length) return 0;

    return products.reduce((sum, product) => sum + Number(product.carbon_saving_value || 0), 0) / products.length;
  }, [products, stats.average_carbon_saved]);

  const averageEcoScore = useMemo(() => {
    if (stats.average_eco_score !== undefined && stats.average_eco_score !== null) {
      return Number(stats.average_eco_score || 0);
    }

    if (!products.length) return 0;

    return products.reduce((sum, product) => sum + Number(product.eco_score || 0), 0) / products.length;
  }, [products, stats.average_eco_score]);

  const removeProduct = async (productId) => {
    if (!window.confirm("Delete this product?")) return;

    try {
      setError("");
      setSuccess("");
      await deleteSellerProduct(productId);
      setSuccess("Product deleted.");
      await loadProducts();
    } catch (err) {
      setError(getErrorMessage(err, "Failed to delete product."));
    }
  };

  const toggleProduct = async (product) => {
    try {
      setError("");
      setSuccess("");
      const formData = new FormData();
      formData.append("is_active", product.is_active ? "0" : "1");
      await updateSellerProduct(product.id, formData);
      setSuccess(product.is_active ? "Product moved to drafts." : "Product published.");
      await loadProducts();
    } catch (err) {
      setError(getErrorMessage(err, "Failed to update product status."));
    }
  };

  return (
    <MarketplaceDashboardShell
      title="Product Inventory"
      subtitle="Manage your ecological catalog. Eco score and carbon savings are generated by AI."
      actions={
        <>
          <label className="seller-products-search">
            <span className="material-symbols-outlined">search</span>
            <input
              type="search"
              placeholder="Search inventory..."
              value={query}
              onChange={(event) => setQuery(event.target.value)}
            />
          </label>
          <Link to="/seller/products/new" className="mp-btn seller-add-product-btn">
            <span className="material-symbols-outlined">add</span>
            Add New Product
          </Link>
        </>
      }
    >
      <div className="seller-products-page">
        {loading ? (
          <StateBlock title="Loading products...">Getting your store inventory.</StateBlock>
        ) : error && products.length === 0 ? (
          <StateBlock title="Products unavailable" tone="error">
            {error}
          </StateBlock>
        ) : (
          <>
            {error && <div className="mp-alert error">{error}</div>}
            {success && <div className="mp-alert success">{success}</div>}

            <section className="seller-products-stats">
              <article className="seller-products-stat-card is-blue">
                <span className="material-symbols-outlined is-filled">co2</span>
                <p>Average Carbon Saved</p>
                <strong>{averageCarbonSaved.toFixed(1)} kg</strong>
                <small>Per product / month</small>
              </article>
              <article className="seller-products-stat-card is-primary">
                <span className="material-symbols-outlined is-filled">eco</span>
                <p>Average Eco Score</p>
                <strong>{Math.round(averageEcoScore)}/100</strong>
                <small>{averageEcoScore ? getEcoLabel(averageEcoScore) : "Pending AI analysis"}</small>
              </article>
            </section>

            <section className="seller-products-card">
              <div className="seller-products-filterbar">
                <div className="seller-products-tabs">
                  {statusFilters.map((item) => (
                    <button
                      key={item.key}
                      type="button"
                      className={filter === item.key ? "active" : ""}
                      onClick={() => setFilter(item.key)}
                    >
                      {item.label}
                    </button>
                  ))}
                </div>
                <div className="seller-products-toolbar-actions">
                  <button type="button">
                    <span className="material-symbols-outlined">filter_alt</span>
                    Filter
                  </button>
                  <button type="button">
                    <span className="material-symbols-outlined">sort</span>
                    Sort
                  </button>
                </div>
              </div>

              {filteredProducts.length === 0 ? (
                <StateBlock
                  title="No products match this view"
                  action={
                    <Link to="/seller/products/new" className="mp-btn">
                      Add Your First Product
                    </Link>
                  }
                >
                  Create a listing and EcoTrack AI will generate the eco score and CO₂ saving.
                </StateBlock>
              ) : (
                <div className="seller-products-table-wrap">
                  <table className="seller-products-table">
                    <thead>
                      <tr>
                        <th>Product</th>
                        <th>Category</th>
                        <th>Eco Score</th>
                        <th>Carbon Saved</th>
                        <th>Inventory</th>
                        <th>Price</th>
                        <th>Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      {filteredProducts.map((product) => (
                        <tr key={product.id} className={!product.is_active ? "is-muted" : ""}>
                          <td>
                            <div className="seller-product-name-cell">
                              <div className="seller-product-thumb xs-table">
                                <MarketplaceImage
                                  product={product}
                                  alt={product.name}
                                  seed={`seller-product-${product.id}`}
                                />
                              </div>
                              <div>
                                <Link to={`/marketplace/products/${product.slug}`}>{product.name}</Link>
                                <small>{product.sku ? `SKU: ${product.sku}` : `ID: PRO-${product.id}`}</small>
                              </div>
                            </div>
                          </td>
                          <td>
                            <span className="seller-category-pill">
                              {product.category || "Eco Product"}
                            </span>
                          </td>
                          <td>
                            <div className="seller-eco-score-cell">
                              <b>{product.eco_score || "--"}</b>
                              <span>{getEcoLabel(product.eco_score)}</span>
                            </div>
                          </td>
                          <td>
                            <strong>{Number(product.carbon_saving_value || 0).toFixed(1)}kg</strong>
                            <small>/ month</small>
                          </td>
                          <td>
                            <strong>{product.stock}</strong>
                            <small> pcs</small>
                          </td>
                          <td>{formatCurrency(product.price)}</td>
                          <td>
                            <div className="seller-products-actions">
                              <Link to={`/seller/products/${product.id}/edit`} title="Edit product">
                                <span className="material-symbols-outlined">edit_square</span>
                              </Link>
                              <button type="button" onClick={() => toggleProduct(product)} title={product.is_active ? "Move to drafts" : "Publish"}>
                                <span className="material-symbols-outlined">
                                  {product.is_active ? "visibility_off" : "visibility"}
                                </span>
                              </button>
                              <button type="button" className="danger" onClick={() => removeProduct(product.id)} title="Delete product">
                                <span className="material-symbols-outlined">delete</span>
                              </button>
                            </div>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}

              <footer className="seller-products-footer">
                <p>Showing {filteredProducts.length} of {products.length} items</p>
                <div>
                  <button type="button" disabled>
                    <span className="material-symbols-outlined">chevron_left</span>
                  </button>
                  <button type="button" className="active">1</button>
                  <button type="button" disabled>
                    <span className="material-symbols-outlined">chevron_right</span>
                  </button>
                </div>
              </footer>
            </section>
          </>
        )}
      </div>
    </MarketplaceDashboardShell>
  );
}
